INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (96, 'Пластины', 2);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (2, 'Токарный', 1);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (3, 'Фрезерный', 1);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (1, 'Главная', 0);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (4, 'Радиусная фреза', 3);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (5, 'Концевая фреза', 3);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (6, 'Универсальный', 1);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (7, 'Радиусная фреза', 3);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (8, 'Резьбовая фреза', 3);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (9, 'Фасонная фреза', 3);
INSERT INTO "tool_tree" ("id", "name", "id_parent") VALUES (10, 'Корпусная фреза', 3);
