INSERT INTO "tool_params" ("id", "info") VALUES (4, 'Ширина');
INSERT INTO "tool_params" ("id", "info") VALUES (5, 'Габарит');
INSERT INTO "tool_params" ("id", "info") VALUES (6, 'Шаг');
INSERT INTO "tool_params" ("id", "info") VALUES (10, 'Диаметр хвостовика');
INSERT INTO "tool_params" ("id", "info") VALUES (9, 'Порядковый номер');
INSERT INTO "tool_params" ("id", "info") VALUES (7, 'Длинна общая');
INSERT INTO "tool_params" ("id", "info") VALUES (8, 'Длинна рабочей части');
INSERT INTO "tool_params" ("id", "info") VALUES (1, 'Тип');
INSERT INTO "tool_params" ("id", "info") VALUES (2, 'Группа');
INSERT INTO "tool_params" ("id", "info") VALUES (3, 'Материал');
INSERT INTO "tool_params" ("id", "info") VALUES (11, 'Диаметр');
INSERT INTO "tool_params" ("id", "info") VALUES (12, 'Радиус');
INSERT INTO "tool_params" ("id", "info") VALUES (13, 'Геометрия');
