INSERT INTO "tool_group" ("id", "name") VALUES (100, '№9 канавочная');
INSERT INTO "tool_group" ("id", "name") VALUES (101, 'корпусное');
INSERT INTO "tool_group" ("id", "name") VALUES (102, 'проходной');
INSERT INTO "tool_group" ("id", "name") VALUES (103, 'расточной');
INSERT INTO "tool_group" ("id", "name") VALUES (104, 'расточной обратный');
INSERT INTO "tool_group" ("id", "name") VALUES (71, 'HSS');
INSERT INTO "tool_group" ("id", "name") VALUES (72, 'для глухих отверстий');
INSERT INTO "tool_group" ("id", "name") VALUES (73, 'для сквозных отверстий');
INSERT INTO "tool_group" ("id", "name") VALUES (76, 'расточная резьбовая');
INSERT INTO "tool_group" ("id", "name") VALUES (77, 'проходная резьбовая');
INSERT INTO "tool_group" ("id", "name") VALUES (78, 'для корпусных сверел');
INSERT INTO "tool_group" ("id", "name") VALUES (81, '№6. 35 градусов двухгранная  "рыбка".');
INSERT INTO "tool_group" ("id", "name") VALUES (90, '№14 канавочная');
INSERT INTO "tool_group" ("id", "name") VALUES (91, '№13 канавочная');
INSERT INTO "tool_group" ("id", "name") VALUES (92, '№12 канавочная');
INSERT INTO "tool_group" ("id", "name") VALUES (93, '№11 канавочная');
INSERT INTO "tool_group" ("id", "name") VALUES (94, '№6 35 градусов четырехгранная "рыбка".');
INSERT INTO "tool_group" ("id", "name") VALUES (95, '№5. 55 градусов 4х-гранная ');
INSERT INTO "tool_group" ("id", "name") VALUES (1, 'Главная');
INSERT INTO "tool_group" ("id", "name") VALUES (99, '№21. двухгранная');
INSERT INTO "tool_group" ("id", "name") VALUES (87, '№2. двухгранная');
INSERT INTO "tool_group" ("id", "name") VALUES (85, '№4. 55 градусов двухгранная ');
INSERT INTO "tool_group" ("id", "name") VALUES (89, '№3. двухгранная');
INSERT INTO "tool_group" ("id", "name") VALUES (96, '№4. 55 градусов двухгранная ');
